import { type DropdownChoice } from '@companion-module/base'
import { ExpireTime, PasteFormat, Publicity } from './enums.js'

export const DropdownExpire: DropdownChoice[] = [
	{ id: ExpireTime.Never, label: 'Never' },
	{ id: ExpireTime.TenMinutes, label: '10 Minutes' },
	{ id: ExpireTime.Hour, label: '1 Hour' },
	{ id: ExpireTime.Day, label: '1 Day' },
	{ id: ExpireTime.OneWeek, label: '1 Week' },
	{ id: ExpireTime.TwoWeeks, label: '2 Weeks' },
	{ id: ExpireTime.Month, label: '1 Month' },
	{ id: ExpireTime.SixMonths, label: '6 Months' },
	{ id: ExpireTime.Year, label: '1 Year' },
]

export const DropdownPrivate: DropdownChoice[] = [
	{ id: Publicity.Public, label: 'Public' },
	{ id: Publicity.Unlisted, label: 'Unlisted' },
	{ id: Publicity.Private, label: 'Private' },
]

export const DropdownPasteFormat: DropdownChoice[] = [
	{ id: PasteFormat.FourCS, label: '4CS' },
	{ id: PasteFormat.SixFiveZeroTwoAcme, label: '6502 ACME Cross Assembler' },
	{ id: PasteFormat.SixFiveZeroTwoKickAssembler, label: '6502 Kick Assembler' },
	{ id: PasteFormat.SixFiveZeroTwoTasm, label: '6502 TASM/64TASS' },
	{ id: PasteFormat.ABAP, label: 'ABAP' },
	{ id: PasteFormat.ActionScript, label: 'ActionScript' },
	{ id: PasteFormat.ActionScript3, label: 'ActionScript 3' },
	{ id: PasteFormat.Ada, label: 'Ada' },
	{ id: PasteFormat.AIMMS, label: 'AIMMS' },
	{ id: PasteFormat.Algol68, label: 'ALGOL 68' },
	{ id: PasteFormat.ApacheLog, label: 'Apache Log' },
	{ id: PasteFormat.AppleScript, label: 'AppleScript' },
	{ id: PasteFormat.AptSources, label: 'APT Sources' },
	{ id: PasteFormat.Arduino, label: 'Arduino' },
	{ id: PasteFormat.ARM, label: 'ARM' },
	{ id: PasteFormat.ASM_NASM, label: 'ASM (NASM)' },
	{ id: PasteFormat.ASP, label: 'ASP' },
	{ id: PasteFormat.Asymptote, label: 'Asymptote' },
	{ id: PasteFormat.Autohotkey, label: 'Autohotkey' },
	{ id: PasteFormat.AutoIt, label: 'AutoIt' },
	{ id: PasteFormat.Avisynth, label: 'Avisynth' },
	{ id: PasteFormat.Awk, label: 'Awk' },
	{ id: PasteFormat.BascomAVR, label: 'Bascom AVR' },
	{ id: PasteFormat.Bash, label: 'Bash' },
	{ id: PasteFormat.Basic4GL, label: 'Basic4GL' },
	{ id: PasteFormat.Batch, label: 'Batch' },
	{ id: PasteFormat.BibTex, label: 'BibTex' },
	{ id: PasteFormat.Biltz3D, label: 'Biltz3D' },
	{ id: PasteFormat.BlitzBasic, label: 'Blitz Basic' },
	{ id: PasteFormat.BlitzMax, label: 'BlitzMax' },
	{ id: PasteFormat.BNF, label: 'BNF' },
	{ id: PasteFormat.BOO, label: 'BOO' },
	{ id: PasteFormat.BrainFuck, label: 'BrainFuck' },
	{ id: PasteFormat.C, label: 'C' },
	{ id: PasteFormat.Csharp, label: 'C#' },
	{ id: PasteFormat.CWinApi, label: 'C (WinAPI)' },
	{ id: PasteFormat.Cpp, label: 'C++' },
	{ id: PasteFormat.CppWinApi, label: 'C++ (WinAPI)' },
	{ id: PasteFormat.CppQt, label: 'C++ (with Qt extensions)' },
	{ id: PasteFormat.CLoadRunner, label: 'C: LoadRunner' },
	{ id: PasteFormat.CadDcl, label: 'CAD DCL' },
	{ id: PasteFormat.CadLISP, label: 'CAD LISP' },
	{ id: PasteFormat.Ceylon, label: 'Ceylon' },
	{ id: PasteFormat.CFDG, label: 'CFDG' },
	{ id: PasteFormat.CMacs, label: 'C for Macs' },
	{ id: PasteFormat.ChaiScript, label: 'ChaiScript' },
	{ id: PasteFormat.Chapel, label: 'Chapel' },
	{ id: PasteFormat.CIL, label: 'C Intermediate Language' },
	{ id: PasteFormat.Clojure, label: 'Clojure' },
	{ id: PasteFormat.CloneC, label: 'Clone C' },
	{ id: PasteFormat.CloneCpp, label: 'Clone C++' },
	{ id: PasteFormat.CMake, label: 'CMake' },
	{ id: PasteFormat.COBOL, label: 'COBOL' },
	{ id: PasteFormat.CoffeeScript, label: 'CoffeeScript' },
	{ id: PasteFormat.ColdFusion, label: 'ColdFusion' },
	{ id: PasteFormat.CSS, label: 'CSS' },
	{ id: PasteFormat.Cuesheet, label: 'Cuesheet' },
	{ id: PasteFormat.D, label: 'D' },
	{ id: PasteFormat.Dart, label: 'Dart' },
	{ id: PasteFormat.DCL, label: 'DCL' },
	{ id: PasteFormat.DCPU16, label: 'DCPU-16' },
	{ id: PasteFormat.DCS, label: 'DCS' },
	{ id: PasteFormat.Delphi, label: 'Delphi' },
	{ id: PasteFormat.DelphiPrism, label: 'Delphi Prism (Oxygene)' },
	{ id: PasteFormat.Diff, label: 'Diff' },
	{ id: PasteFormat.DIV, label: 'DIV' },
	{ id: PasteFormat.DOT, label: 'DOT' },
	{ id: PasteFormat.E, label: 'E' },
	{ id: PasteFormat.Easytrieve, label: 'Easytrieve' },
	{ id: PasteFormat.EcmaScript, label: 'ECMA Script' },
	{ id: PasteFormat.Eiffel, label: 'Eiffel' },
	{ id: PasteFormat.Email, label: 'Email' },
	{ id: PasteFormat.EPC, label: 'EPC' },
	{ id: PasteFormat.Erlang, label: 'Erlang' },
	{ id: PasteFormat.Euphoria, label: 'Euphoria' },
	{ id: PasteFormat.Fsharp, label: 'F#' },
	{ id: PasteFormat.Falcon, label: 'Falcon' },
	{ id: PasteFormat.Filemaker, label: 'Filemaker' },
	{ id: PasteFormat.FOLanguage, label: 'FO Language' },
	{ id: PasteFormat.FormulaOne, label: 'Formula One' },
	{ id: PasteFormat.Fortran, label: 'Fortran' },
	{ id: PasteFormat.FreeBasic, label: 'FreeBasic' },
	{ id: PasteFormat.FreeSWITCH, label: 'FreeSWITCH' },
	{ id: PasteFormat.GAMBAS, label: 'GAMBAS' },
	{ id: PasteFormat.GameMaker, label: 'GameMaker' },
	{ id: PasteFormat.GBD, label: 'GBD' },
	{ id: PasteFormat.GDScript, label: 'GDScript' },
	{ id: PasteFormat.Genero, label: 'Genero' },
	{ id: PasteFormat.Genie, label: 'Genie' },
	{ id: PasteFormat.GetText, label: 'GetText' },
	{ id: PasteFormat.Go, label: 'Go' },
	{ id: PasteFormat.GodotGLSL, label: 'Godot GLSL' },
	{ id: PasteFormat.Groovy, label: 'Groovy' },
	{ id: PasteFormat.GwBasic, label: 'GwBasic' },
	{ id: PasteFormat.Haskell, label: 'Haskell' },
	{ id: PasteFormat.Haxe, label: 'Haxe' },
	{ id: PasteFormat.HicEst, label: 'HicEst' },
	{ id: PasteFormat.HQ9Plus, label: 'HQ9 Plus' },
	{ id: PasteFormat.HTML, label: 'HTML' },
	{ id: PasteFormat.HTML5, label: 'HTML 5' },
	{ id: PasteFormat.Icon, label: 'Icon' },
	{ id: PasteFormat.IDL, label: 'IDL' },
	{ id: PasteFormat.INI, label: 'INI' },
	{ id: PasteFormat.InnoScript, label: 'Inno Script' },
	{ id: PasteFormat.InterCal, label: 'INTERCAL' },
	{ id: PasteFormat.IO, label: 'IO' },
	{ id: PasteFormat.IspfPanel, label: 'ISPF Panel Definition' },
	{ id: PasteFormat.J, label: 'J' },
	{ id: PasteFormat.Java, label: 'Java' },
	{ id: PasteFormat.Java5, label: 'Java 5' },
	{ id: PasteFormat.JavaScript, label: 'JavaScript' },
	{ id: PasteFormat.JCL, label: 'JCL' },
	{ id: PasteFormat.JQuery, label: 'jQuery' },
	{ id: PasteFormat.JSON, label: 'JSON' },
	{ id: PasteFormat.Julia, label: 'Julia' },
	{ id: PasteFormat.KiXtart, label: 'KiXtart' },
	{ id: PasteFormat.Kotlin, label: 'Kotlin' },
	{ id: PasteFormat.KSP, label: 'KSP (Kontakt Script)' },
	{ id: PasteFormat.Latex, label: 'Latex' },
	{ id: PasteFormat.LDIF, label: 'LDIF' },
	{ id: PasteFormat.LibertyBasic, label: 'Liberty BASIC' },
	{ id: PasteFormat.LindenScripting, label: 'Linden Scripting' },
	{ id: PasteFormat.Lisp, label: 'Lisp' },
	{ id: PasteFormat.LLVM, label: 'LLVM' },
	{ id: PasteFormat.LocoBasic, label: 'Loco Basic' },
	{ id: PasteFormat.LogTalk, label: 'Logtalk' },
	{ id: PasteFormat.LOLCode, label: 'LOL Code' },
	{ id: PasteFormat.LotusFormulas, label: 'Lotus Formulas' },
	{ id: PasteFormat.LotusScript, label: 'Lotus Script' },
	{ id: PasteFormat.LScript, label: 'LScript' },
	{ id: PasteFormat.Lua, label: 'Lua' },
	{ id: PasteFormat.M68kAssm, label: 'M68000 Assembler' },
	{ id: PasteFormat.MagikSF, label: 'MagikSF' },
	{ id: PasteFormat.Make, label: 'Make' },
	{ id: PasteFormat.MapBasic, label: 'MapBasic' },
	{ id: PasteFormat.MarkDown, label: 'Markdown' },
	{ id: PasteFormat.MatLab, label: 'MatLab' },
	{ id: PasteFormat.Mercury, label: 'Mercury' },
	{ id: PasteFormat.MetaPost, label: 'MetaPost' },
	{ id: PasteFormat.mIRC, label: 'mIRC' },
	{ id: PasteFormat.MIXAssm, label: 'MIX Assembler' },
	{ id: PasteFormat.MK6152, label: 'MK-61/52' },
	{ id: PasteFormat.Modula2, label: 'Modula 2' },
	{ id: PasteFormat.Modula3, label: 'Modula 3' },
	{ id: PasteFormat.Motorola68k, label: 'Motorola 68000 HiSoft Dev' },
	{ id: PasteFormat.MPASM, label: 'MPASM' },
	{ id: PasteFormat.MXML, label: 'MXML' },
	{ id: PasteFormat.MYSQL, label: 'MYSQL' },
	{ id: PasteFormat.Nagios, label: 'Nagios' },
	{ id: PasteFormat.NetRexx, label: 'NetRexx' },
	{ id: PasteFormat.newLISP, label: 'newLISP' },
	{ id: PasteFormat.Nginx, label: 'Nginx' },
	{ id: PasteFormat.Nim, label: 'Nim' },
	{ id: PasteFormat.NullSoftInstaller, label: 'NullSoft Installer' },
	{ id: PasteFormat.Oberon2, label: 'Oberon 2' },
	{ id: PasteFormat.ObjeckProgramming, label: 'Objeck Programming Langua' },
	{ id: PasteFormat.ObjectiveC, label: 'Objective C' },
	{ id: PasteFormat.OCaml, label: 'OCaml' },
	{ id: PasteFormat.OCamlBrief, label: 'OCaml Brief' },
	{ id: PasteFormat.Octave, label: 'Octave' },
	{ id: PasteFormat.OpenBSDPacketFilter, label: 'Open BSD Packet Filter' },
	{ id: PasteFormat.OpenGLShading, label: 'Open GL Shading' },
	{ id: PasteFormat.OpenObjectRexx, label: 'Open Object Rexx' },
	{ id: PasteFormat.OpenofficeBASIC, label: 'Openoffice BASIC' },
	{ id: PasteFormat.Oracle8, label: 'Oracle 8' },
	{ id: PasteFormat.Oracle11, label: 'Oracle 11' },
	{ id: PasteFormat.Oz, label: 'Oz' },
	{ id: PasteFormat.ParaSail, label: 'ParaSail' },
	{ id: PasteFormat.PariGP, label: 'Pari/GP' },
	{ id: PasteFormat.Pascal, label: 'Pascal' },
	{ id: PasteFormat.Pawn, label: 'Pawn' },
	{ id: PasteFormat.PCRE, label: 'PCRE' },
	{ id: PasteFormat.Per, label: 'Per' },
	{ id: PasteFormat.Perl, label: 'Perl' },
	{ id: PasteFormat.Perl6, label: 'Perl 6' },
	{ id: PasteFormat.Phix, label: 'Phix' },
	{ id: PasteFormat.PHP, label: 'PHP' },
	{ id: PasteFormat.PHP_Brief, label: 'PHP Brief' },
	{ id: PasteFormat.Pic16, label: 'Pic 16' },
	{ id: PasteFormat.Pike, label: 'Pike' },
	{ id: PasteFormat.PixelBender, label: 'Pixel Bender' },
	{ id: PasteFormat.PLI, label: 'PL/I' },
	{ id: PasteFormat.PLSQL, label: 'PL/SQL' },
	{ id: PasteFormat.PostgreSQL, label: 'PostgreSQL' },
	{ id: PasteFormat.PostScript, label: 'PostScript' },
	{ id: PasteFormat.PovRay, label: 'POV-Ray' },
	{ id: PasteFormat.PowerBuilder, label: 'PowerBuilder' },
	{ id: PasteFormat.PowerShell, label: 'PowerShell' },
	{ id: PasteFormat.ProFTPd, label: 'ProFTPd' },
	{ id: PasteFormat.Progress, label: 'Progress' },
	{ id: PasteFormat.Prolog, label: 'Prolog' },
	{ id: PasteFormat.Properties, label: 'Properties' },
	{ id: PasteFormat.ProvideX, label: 'ProvideX' },
	{ id: PasteFormat.Puppet, label: 'Puppet' },
	{ id: PasteFormat.PureBasic, label: 'PureBasic' },
	{ id: PasteFormat.PyCon, label: 'PyCon' },
	{ id: PasteFormat.Python, label: 'Python' },
	{ id: PasteFormat.PythonForS60, label: 'Python for S60' },
	{ id: PasteFormat.QKDBp, label: 'Q/KDB+' },
	{ id: PasteFormat.QBasic, label: 'QBasic' },
	{ id: PasteFormat.QML, label: 'QML' },
	{ id: PasteFormat.R, label: 'R' },
	{ id: PasteFormat.Racket, label: 'Racket' },
	{ id: PasteFormat.Rails, label: 'Rails' },
	{ id: PasteFormat.RBScript, label: 'RBScript' },
	{ id: PasteFormat.REBOL, label: 'REBOL' },
	{ id: PasteFormat.REG, label: 'REG' },
	{ id: PasteFormat.Rexx, label: 'Rexx' },
	{ id: PasteFormat.Robots, label: 'Robots' },
	{ id: PasteFormat.RoffManpage, label: 'Roff Manpage' },
	{ id: PasteFormat.RPMSpec, label: 'RPM Spec' },
	{ id: PasteFormat.Ruby, label: 'Ruby' },
	{ id: PasteFormat.RubyGnuplot, label: 'Ruby Gnuplot' },
	{ id: PasteFormat.Rust, label: 'Rust' },
	{ id: PasteFormat.SAS, label: 'SAS' },
	{ id: PasteFormat.Scala, label: 'Scala' },
	{ id: PasteFormat.Scheme, label: 'Scheme' },
	{ id: PasteFormat.Scilab, label: 'Scilab' },
	{ id: PasteFormat.SCL, label: 'SCL' },
	{ id: PasteFormat.SdlBasic, label: 'SdlBasic' },
	{ id: PasteFormat.Smalltalk, label: 'Smalltalk' },
	{ id: PasteFormat.Smarty, label: 'Smarty' },
	{ id: PasteFormat.SPARK, label: 'SPARK' },
	{ id: PasteFormat.SPARQL, label: 'SPARQL' },
	{ id: PasteFormat.SQF, label: 'SQF' },
	{ id: PasteFormat.SQL, label: 'SQL' },
	{ id: PasteFormat.SSHConfig, label: 'SSH Config' },
	{ id: PasteFormat.StandardML, label: 'StandardML' },
	{ id: PasteFormat.StoneScript, label: 'StoneScript' },
	{ id: PasteFormat.SuperCollider, label: 'Super Collider' },
	{ id: PasteFormat.Swift, label: 'Swift' },
	{ id: PasteFormat.SystemVerilog, label: 'System Verilog' },
	{ id: PasteFormat.TSQL, label: 'TSQL' },
	{ id: PasteFormat.TCL, label: 'TCL' },
	{ id: PasteFormat.TeraTerm, label: 'TeraTerm' },
	{ id: PasteFormat.TeXgraph, label: 'TeXgraph' },
	{ id: PasteFormat.ThinBasic, label: 'ThinBasic' },
	{ id: PasteFormat.TypeScript, label: 'TypeScript' },
	{ id: PasteFormat.TypoScript, label: 'TypoScript' },
	{ id: PasteFormat.Unicon, label: 'Unicon' },
	{ id: PasteFormat.UnrealScript, label: 'UnrealScript' },
	{ id: PasteFormat.UPC, label: 'UPC' },
	{ id: PasteFormat.Urbi, label: 'Urbi' },
	{ id: PasteFormat.Vala, label: 'Vala' },
	{ id: PasteFormat.VB_Net, label: 'VB.Net' },
	{ id: PasteFormat.VBScript, label: 'VB Script' },
	{ id: PasteFormat.Vedit, label: 'Vedit' },
	{ id: PasteFormat.VeriLog, label: 'VeriLog' },
	{ id: PasteFormat.VHDL, label: 'VHDL' },
	{ id: PasteFormat.VIM, label: 'VIM' },
	{ id: PasteFormat.VisualBasic, label: 'VisualBasic' },
	{ id: PasteFormat.VisualFoxPro, label: 'VisualFoxPro' },
	{ id: PasteFormat.VisualProLog, label: 'Visual Pro Log' },
	{ id: PasteFormat.WhiteSpace, label: 'WhiteSpace' },
	{ id: PasteFormat.WHOIS, label: 'WHOIS' },
	{ id: PasteFormat.Winbatch, label: 'Winbatch' },
	{ id: PasteFormat.XBasic, label: 'XBasic' },
	{ id: PasteFormat.XML, label: 'XML' },
	{ id: PasteFormat.Xojo, label: 'Xojo' },
	{ id: PasteFormat.XorgConfig, label: 'Xorg Config' },
	{ id: PasteFormat.XPP, label: 'XPP' },
	{ id: PasteFormat.YAML, label: 'YAML' },
	{ id: PasteFormat.YARA, label: 'YARA' },
	{ id: PasteFormat.Z80Asm, label: 'Z80 Assembler' },
	{ id: PasteFormat.ZXBasic, label: 'ZXBasic' },
]
